### ISSUE TITLE
Additional mergify rules

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-components#8472]
Some ideas for additional mergify rules.

**Dismissing reviews for pull requests that have changed and are not by a "core" member**
Something like:
```yaml
  - name: Reset PR of non-core contributors
    conditions:
      - author!=@mozilla-mobile/act
      - author!=@mozilla-mobile/sv-eng
      - author!=@mozilla-mobile/apt
      - author!=@mozilla-mobile/releng
      - author!=@mozilla-mobile/telemetry
    actions:
      dismiss_reviews: {}
```

**Adding a work in progress label to WIP/wip PRs**

```yaml
  - name: Add WIP label
    conditions:
      - title~=^(wip|WIP).*
    actions:
      label:
        add: ["work in progress"]
```

**Not merging PRs that are draft or have the WIP label**
(Needs modification of the merge rule)

**Adding [needs review] label to new PRs that are not draft/WIP**
TBD.

**Post message when PR has conflicts**
```yaml
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request is now in conflict :(
      label:
        add:
          - conflict
  - name: remove conflict label if not needed
    conditions:
      - -conflict
    actions:
      label:
        remove:
          - conflict
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-7342)
