### ISSUE TITLE
Create-Release Workflow does not trigger

### ISSUE THREAD

**Issue by st3fan** [mozilla-mobile/android-components#9155]
Even though a GV Beta and version bump landed with #9150 the [create-release.yml)(https://github.com/mozilla-mobile/android-components/blob/master/.github/workflows/create-release.yml) workflow did not trigger.

It has the following rule, which should work in theory:

```yaml
on:
  push:
    branches:
      - 'releases/**'
    paths:
      - '.buildconfig.yml'
```

Let's run this on a fork to see why this fails.
